"""Initial migration

Revision ID: 1cd98f7b64c6
Revises: 547c7dd88932
Create Date: 2024-07-14 16:54:38.779122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cd98f7b64c6'
down_revision: Union[str, None] = '547c7dd88932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_members', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_members', 'is_admin')
    # ### end Alembic commands ###
