version: '3.8'

services:
  web:
    build:
      context: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres2191202
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=be19db.c38keuoas3pn.us-east-1.rds.amazonaws.com
      - REDIS_HOST=be19redis-ogxw1i.serverless.use1.cache.amazonaws.com
      - REDIS_PORT=6379

  celery:
    build:
      context: .
    command: celery -A app.celery:celery worker --loglevel=INFO
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres2191202
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=be19db.c38keuoas3pn.us-east-1.rds.amazonaws.com
      - REDIS_HOST=be19redis-ogxw1i.serverless.use1.cache.amazonaws.com
      - REDIS_PORT=6379

  celery-beat:
    build:
      context: .
    command: celery -A app.celery:celery beat --loglevel=INFO
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres2191202
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=be19db.c38keuoas3pn.us-east-1.rds.amazonaws.com
      - REDIS_HOST=be19redis-ogxw1i.serverless.use1.cache.amazonaws.com
      - REDIS_PORT=6379

  flower:
    image: mher/flower:latest
    build:
      context: .
    command: celery -A app.celery:celery flower --port=5555
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres2191202
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=be19db.c38keuoas3pn.us-east-1.rds.amazonaws.com
      - REDIS_HOST=be19redis-ogxw1i.serverless.use1.cache.amazonaws.com
      - REDIS_PORT=6379
