version: '3.8'

services:
  web:
    build:
      context: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB
      - POSTGRES_PORT
      - POSTGRES_HOST
      - REDIS_HOST
      - REDIS_PORT

  celery:
    build:
      context: .
    command: celery -A app.celery:celery worker --loglevel=INFO
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB
      - POSTGRES_PORT
      - POSTGRES_HOST
      - REDIS_HOST
      - REDIS_PORT

  celery-beat:
    build:
      context: .
    command: celery -A app.celery:celery beat --loglevel=INFO
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB
      - POSTGRES_PORT
      - POSTGRES_HOST
      - REDIS_HOST
      - REDIS_PORT
    depends_on:
      - celery

  flower:
    image: mher/flower:latest
    build:
      context: .
    command: celery -A app.celery:celery flower --port=5555
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB
      - POSTGRES_PORT
      - POSTGRES_HOST
      - REDIS_HOST
      - REDIS_PORT
    depends_on:
      - celery

  db-client:
    image: postgres:latest
    command: [ "psql", "-h", "be19db.c38keuoas3pn.us-east-1.rds.amazonaws.com", "-p", "5432", "-U", "postgres", "-d", "BE19" ]
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    stdin_open: true
    tty: true

  redis-client:
    image: redis:latest
    command: [ "redis-cli", "-h", "be19redis-ogxw1i.serverless.use1.cache.amazonaws.com", "-p", "6379" ]
    stdin_open: true
    tty: true
