version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build:
      context: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB
      - POSTGRES_PORT
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - REDIS_PORT
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
    command: celery -A app.celery:celery worker --loglevel=INFO
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB
      - POSTGRES_PORT
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - REDIS_PORT
    depends_on:
      - db
      - redis

  celery-beat:
    build:
      context: .
    command: celery -A app.celery:celery beat --loglevel=INFO
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB
      - POSTGRES_PORT
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - REDIS_PORT
    depends_on:
      - db
      - redis
      - celery

  flower:
    image: mher/flower:latest
    build:
      context: .
    command: celery -A app.celery:celery flower --port=5555
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB
      - POSTGRES_PORT
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - REDIS_PORT
    depends_on:
      - db
      - redis
      - celery

volumes:
  postgres_data: