name: CI/CD Pipeline

on:
  push:
    branches:
      - be_19_add_aws_structure

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Run Docker Compose
        run: docker-compose up -d --build

      - name: Run tests inside Docker container
        run: docker-compose exec web poetry run pytest --maxfail=1 --disable-warnings -q

  deploy:
    runs-on: ubuntu-latest
    needs: setup-and-test
    env:
      BRANCH_NAME: be_19_add_aws_structure

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 instance
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/ec2-key.pem
          chmod 600 /tmp/ec2-key.pem

          ssh -o StrictHostKeyChecking=no -i /tmp/ec2-key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} <<EOF
              cd internship_meduzzen_backend

              echo "Pulling latest code from git repository..."
              git fetch origin
              git checkout $BRANCH_NAME
              git pull origin $BRANCH_NAME

              echo "Stopping and removing existing containers..."
              docker-compose down || true

              echo "Building and running Docker Compose with the latest images..."
              docker-compose up -d --build
          EOF