name: CI/CD Pipeline

on:
  push:
    branches:
      - be_19_add_aws_structure

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/webapp:${{ github.sha }}

      - name: Deploy to EC2 instance
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/ec2-key.pem
          chmod 600 /tmp/ec2-key.pem

          ssh -o StrictHostKeyChecking=no -i /tmp/ec2-key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} <<EOF
              cd internship_meduzzen_backend
              
              echo "Pulling latest code from git repository..."
              git pull origin be_20_add_aws_structure

              echo "Building Docker images..."
              docker-compose build

              echo "Stopping and removing existing containers..."
              docker-compose down || true

              echo "Running Docker Compose with the latest images..."
              docker-compose up -d
          EOF